CREATE TABLE TipoFestivo (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Tipo VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Pais (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Festivo (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    IdPais INT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Dia INT NOT NULL,
    Mes INT NOT NULL,
    DiasPascua INT NOT NULL,
    IdTipo INT NOT NULL,
    CONSTRAINT fkFestivo_Pais FOREIGN KEY (IdPais) REFERENCES Pais(Id),
    CONSTRAINT fkFestivo_Tipo FOREIGN KEY (IdTipo) REFERENCES TipoFestivo(Id)
);
